### ISSUE TITLE
PDF is in English, extracted text is in Greek, correct text can be copied from Chrome with no problem

### ISSUE THREAD

**Issue by Lidia321** [galkahana/pdf-text-extraction#16]
Hi

Attached is the example pdf.
Attached is the output of TextExtraction.exe.

The problem description is in the title.

Is it possible to fix it technically  - means extract text as it looks, in English ?
If the answer is yes, is it going or can be fixed soon ?

Thanks and cheers.
Lidia.

[4.pdf](https://github.com/galkahana/pdf-text-extraction/files/11782482/4.pdf)
[aa.txt](https://github.com/galkahana/pdf-text-extraction/files/11782483/aa.txt)

**Comment by galkahana** [comment]
Hi Lidia.
it should be possible to fix this. didn't have time today to look into it...so just briefly but it's just that the font reference is for the text is for some reason a symbol font and not the helvetica font its using. the pdf seems very clear and correct so the code does something wrong. it shouldn't be too hard to find, but i need some time. I reckon at latest i can provide a correction during the weekend, but probably can find time earlier.

**Comment by galkahana** [comment]
#17 should take care of this. i'll try to merge soon. but in any case that's the problem

**Comment by galkahana** [comment]
Merged.

**Comment by Lidia321** [comment]
works like a charm.

great and thanks
Lidia.
