### ISSUE TITLE
Fuzz testing the application

### ISSUE THREAD

**Issue by GianniM123** [galkahana/pdf-text-extraction#2]
Hi,

For a universty-project we chose to fuzz-test your application.

During this tests we found some flaws in the application. The PDFs which causes some crashes can be found here: [pdfs.zip](https://github.com/galkahana/pdf-text-extraction/files/5607801/pdfs.zip)

**Comment by galkahana** [comment]
got motivated to resolve those issues, should be better (well...good) now.
