### ISSUE TITLE
Crash when importing text this -t flag on macOS

### ISSUE THREAD

**Issue by iljukhaput** [galkahana/pdf-text-extraction#25]
If you enable the -t flag, then sometimes there will be a crash on macOS:
```
TextExtraction(710,0x116f10600) malloc: Heap corruption detected, free list is damaged at 0x600002534230
*** Incorrect guard value: 4464114552
TextExtraction(710,0x116f10600) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by galkahana** [comment]
do you have a method of recreating this? does it, for instance, occur on particular input files? or just completely random..say on the same file you sometimes run with -t sometimes and it'll work sometimes and fail some other times?

**Comment by galkahana** [comment]
is this related to the PR - https://github.com/galkahana/pdf-text-extraction/pull/26?
The corrections seems valid then, and i'll merge it. thank you!

**Comment by iljukhaput** [comment]
> or just completely random..say on the same file you sometimes run with -t sometimes and it'll work sometimes and fail some other times?

yes, the failure occurred in this way

> is this related to the PR - https://github.com/galkahana/pdf-text-extraction/pull/26?

and yes, it is

Was glad to help!
